source 'https://rubygems.org'

### RAILS / RUBY ###

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.8'

# Use postgresql as the database for Active Record
gem 'pg'

# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc


# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

### DEVELOPMENT ###

# Use Capistrano for deployment
gem 'capistrano-rails', group: :development

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring', group: :development

# Add a comment summarizing the current schema to the top or bottom of each of your various files
gem 'annotate', '~> 2.6.5'

# Better Errors replaces the standard Rails error page with a much better and more useful error page
gem 'better_errors', group: :development

# REPL and local/instance variable inspection
gem "binding_of_caller", group: :development

gem 'hirb', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

### CSS ###

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

### JAVA ###

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer',  platforms: :ruby

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'

### AUTHENTICATION & AUTHORIZATION ###

# Authentication
gem 'devise', '~> 3.4.1'

# Authorizaton
gem 'pundit'

### FRAMEWORKS ###

# Bootstrap!
gem 'bootstrap-sass', '~> 3.3.1'
#gem 'sass-rails', '>= 3.2'

# Add browser vendor prefixes automatically
gem 'autoprefixer-rails'

gem 'font-awesome-sass'

### Administration ###

gem 'activeadmin', github: 'activeadmin'